# Generated by Django 5.2 on 2025-04-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="annual_cost_option",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional: The cost if paid annually (for comparison).",
                max_digits=10,
                null=True,
            ),
        ),
    ]
