# Generated by Django 5.2 on 2025-04-19 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_annual_cost_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annually", "Annually")],
                        max_length=10,
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
    ]
